In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Iris-f.csv")

In [4]:
df.fillna(method="bfill",inplace=True)

In [5]:
df.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [48]:
from sklearn.feature_selection import SelectKBest

In [49]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.4           3.6            1.4           0.2  Iris-setosa

In [50]:
x=df.iloc[:,0:4] 
y=df.Species 

In [51]:
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.4           3.6            1.4           0.2

In [52]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [53]:
selectk=SelectKBest(chi2,k=2)
selectk.fit_transform(x,y)

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.4, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [55]:
cols=selectk.get_support(indices=True)
cols

array([2, 3], dtype=int64)

In [56]:
new_df=df.iloc[:,cols]

In [57]:
new_df.head()

PetalLengthCm  PetalWidthCm
0            1.4           0.2
1            1.4           0.2
2            1.3           0.2
3            1.5           0.2
4            1.4           0.2

In [58]:
x=df.iloc[:,[0,1,3,4]]
y=df.iloc[:,2]

In [59]:
x.head()

SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0            5.1           3.5           0.2  Iris-setosa
1            4.9           3.0           0.2  Iris-setosa
2            4.7           3.2           0.2  Iris-setosa
3            4.6           3.1           0.2  Iris-setosa
4            5.4           3.6           0.2  Iris-setosa

In [61]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x["Species"]=le.fit_transform(x["Species"])

<ipython-input-61-44d8bd290c56>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Species"]=le.fit_transform(x["Species"])


In [62]:
x.head()

SepalLengthCm  SepalWidthCm  PetalWidthCm  Species
0            5.1           3.5           0.2        0
1            4.9           3.0           0.2        0
2            4.7           3.2           0.2        0
3            4.6           3.1           0.2        0
4            5.4           3.6           0.2        0

In [63]:
selectk=SelectKBest(f_regression,k=2)
selectk.fit_transform(x,y)

array([[0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.4, 0. ],
       [0.3, 0. ],
       [0.3, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.2, 0. ],
       [0.5, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.4, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.1, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.3, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.6, 0. ],
       [0.4, 0. ],
       [0.3, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [1.4, 1. ],
       [1.5, 1. ],
       [1.5,

In [64]:
cols=selectk.get_support(indices=True)
cols

array([2, 3], dtype=int64)

In [65]:
df.corr()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       1.000000     -0.099590       0.870889      0.817528
SepalWidthCm       -0.099590      1.000000      -0.410990     -0.347022
PetalLengthCm       0.870889     -0.410990       1.000000      0.962776
PetalWidthCm        0.817528     -0.347022       0.962776      1.000000

In [6]:
x=df.iloc[:,0:4]

In [8]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
x_new=pca.fit_transform(x)

In [9]:
type(x_new)

numpy.ndarray

In [10]:
new_df=pd.DataFrame(x_new,columns=["comp1","comp2"])

In [11]:
new_df.head()

comp1     comp2
0 -2.683775  0.331738
1 -2.715973 -0.164505
2 -2.889894 -0.131903
3 -2.746601 -0.305910
4 -2.583455  0.601475

In [14]:
y=df.Species


In [15]:
from sklearn.model_selection import train_test_split

In [23]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,shuffle=True)

In [24]:
xtest.shape

(38, 4)

In [25]:
xtrain.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
104            6.5           3.0            5.8           2.2
70             5.9           3.2            4.8           1.8
64             5.6           2.9            3.6           1.3
133            6.3           2.8            5.1           1.5
109            7.2           3.6            6.1           2.5

In [27]:
ytrain.value_counts()

Iris-versicolor    40
Iris-virginica     36
Iris-setosa        36
Name: Species, dtype: int64