In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Iris-f.csv")
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            NaN           3.6            1.4           0.2  Iris-setosa

### Preprocessing

#### Treating the Null Values

In [3]:
# To find the Null Values
df.isna().sum()

SepalLengthCm    2
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     0
Species          2
dtype: int64

In [4]:
df.fillna(method="bfill",inplace=True)

In [5]:
df.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

#### Treat the categorical Variable

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Species"]=le.fit_transform(df["Species"])
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.4           3.6            1.4           0.2        0

#### Feature Scaling

In [7]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
x=df.iloc[:,0:4]
scaled=mm.fit_transform(x)
scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.30555556, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.375     , 0.06779661, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [8]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [9]:
df_new=pd.DataFrame(scaled,columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm','PetalWidthCm'])

In [10]:
df_new.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0       0.222222      0.625000       0.067797      0.041667
1       0.166667      0.416667       0.067797      0.041667
2       0.111111      0.500000       0.050847      0.041667
3       0.083333      0.458333       0.084746      0.041667
4       0.305556      0.666667       0.067797      0.041667

In [11]:
df_new["Species"]=df.Species
df_new.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0       0.222222      0.625000       0.067797      0.041667        0
1       0.166667      0.416667       0.067797      0.041667        0
2       0.111111      0.500000       0.050847      0.041667        0
3       0.083333      0.458333       0.084746      0.041667        0
4       0.305556      0.666667       0.067797      0.041667        0

#### Splitting of Train and Test

In [18]:
from sklearn.model_selection import train_test_split
x=df_new.iloc[:,1:5]
y=df_new.SepalLengthCm
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=1,shuffle=True)

In [19]:
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(120, 4)
(120,)
(30, 4)
(30,)


### Learning

In [20]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

### Evaluation

In [21]:
ypred=lr.predict(xtest)
ypred

array([0.22328593, 0.17836305, 0.54367114, 0.20472954, 0.94911138,
       0.63501189, 0.49761927, 0.32802704, 0.18905694, 0.65266967,
       0.46258826, 0.29751218, 0.69318367, 0.58568191, 0.53805255,
       0.11946997, 0.41325829, 0.55392901, 0.1717386 , 0.09627431,
       0.50604092, 0.55392901, 0.64403171, 0.15416153, 0.78694562,
       0.45526906, 0.30143015, 0.2481822 , 0.6073808 , 0.43091607])

In [26]:
from sklearn.metrics import r2_score, mean_absolute_error
print(r2_score(ytest,ypred))
print(mean_absolute_error(ytest,ypred))

0.7608853181449958
0.08942021167342325


### Prediction

In [23]:
# Unseen Example
xnew=np.array([0.26,0.03,0.06,0]).reshape(1, -1)
mypred=lr.predict(xnew)

In [24]:
mypred

array([-0.00620169])